version: '3.8'

services:
  # 1. GÜVENLİK VE YÖNLENDİRİCİ (8080 PORTUNDA)
  dispatcher:
    build: ./dispatcher
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_URI=mongodb://dispatcher_db:27017/dispatcher_logs
    depends_on:
      - dispatcher_db
      - user_service
      - product_service
      - order_service

  dispatcher_db:
    image: mongo:latest
    container_name: dispatcher_db
    ports:
      - "27017:27017" # Dışarıdan izlenebilmesi için açık tutulabilir (opsiyonel)

  # 2. KULLANICI SERVİSİ
  user_service:
    build: ./user-service
    environment:
      - PORT=3001
      - DB_URI=mongodb://user_db:27017/users
    depends_on:
      - user_db

  user_db:
    image: mongo:latest
    container_name: user_db

  # 3. ÜRÜN SERVİSİ
  product_service:
    build: ./product-service
    environment:
      - PORT=3002
      - DB_URI=mongodb://product_db:27017/products
    depends_on:
      - product_db

  product_db:
    image: mongo:latest
    container_name: product_db

  # 4. SİPARİŞ SERVİSİ (ORDER)
  order_service:
    build: ./order-service
    environment:
      - PORT=3003
      - DB_URI=mongodb://order_db:27017/orders
    depends_on:
      - order_db

  order_db:
    image: mongo:latest
    container_name: order_db

  # 5. YÜK TESTİ (K6) - Profil: load-test ile başlatılır
  k6:
    image: grafana/k6:latest
    profiles: ["load-test"]
    volumes:
      - ./load_test.js:/scripts/load_test.js
      - ./k6-results:/results
    environment:
      - BASE_URL=http://dispatcher:8080
      - K6_INFLUXDB_ORGANIZATION=k6
      - K6_INFLUXDB_BUCKET=k6
      - K6_INFLUXDB_INSECURE_SKIP_TLS_VERIFY=true
    command: run --out influxdb=http://influxdb:8086 --out json=/results/results.json /scripts/load_test.js
    depends_on:
      - dispatcher
      - influxdb

  # 6. VERİ DEPOSU (InfluxDB) - K6 metrikleri buraya akar
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - influxdb_data:/var/lib/influxdb

  # 7. GÖRSEL PANEL (Grafana) - localhost:3000
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data:
